### ISSUE TITLE
What features will this have over SeqViz?

### ISSUE THREAD

**Issue by bugzpodder** [alemastro97/SeqViz-Plus#1]

**Comment by alemastro97** [comment]
Hi @bugzpodder , we have tried to expand the actual SeqViz with:
- Right Click Menu to copy the selected part of the sequence (or choose to copy its complement/reverse complement or translation)
- Add a new viewer named: "Alignment" to compare to dna/aa sequences.

Obviously our intent is to extend the library without going to take credit away from the people who developed SeqViz.
Let me know if I have answered your questions

**Comment by bugzpodder** [comment]
Thank you.  I am looking for a feature that allows one line sequence viewer rather than multiple rows.  I am hoping to [PR back](https://github.com/Lattice-Automation/seqviz/pull/205) to the original seqviz repo at this point
